### ISSUE TITLE
tryItOutEnabled: false is ignored

### ISSUE THREAD

**Issue by Andre601** [blueswen/mkdocs-swagger-ui-tag#12]
Setting `tryItOutEnabled: false` in the plugin's setting is being ignored, since the "Try it out" button is still being displayed and can be toggled.

`mkdocs.yml` settings:
```yaml
plugins:
  - search
  - swagger-ui-tag:
      tryItOutEnabled: false
```
Result:
![grafik](https://user-images.githubusercontent.com/11576465/232874776-a298cca0-118e-43a9-83db-da3b6e16e311.png)

**Comment by blueswen** [comment]
To resolve this issue, you can add an additional option supportedSubmitMethods to your YAML configuration file with an empty array as its value temporary, like so:

```yaml
plugins:
  - swagger-ui-tag:
      tryItOutEnabled: false
      supportedSubmitMethods: []
```

<img width="1343" alt="Swagger UI Tag Demo" src="https://user-images.githubusercontent.com/1564148/233419496-beb03805-833f-4d65-92b8-f06e0cb4473a.png">

I need some time to find out how to fix this issue. It's possible that I may have misunderstood the configuration options outlined in the [Swagger UI documentation](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/), but I'm working to figure it out.
