### ISSUE TITLE
[performance] Looking up every file is slow

### ISSUE THREAD

**Issue by pedro-psb** [blueswen/mkdocs-swagger-ui-tag#25]
Hello, I've noticed that the processing [here](https://github.com/blueswen/mkdocs-swagger-ui-tag/blob/58465ea5057bb9de6bdd0fd488bb8a983aac03b3/mkdocs_swagger_ui_tag/plugin.py#L105) can significantly slows down building the docs, probably because of BeautifulSoup.

On my website, running the plugin added an overhead of about 27s. Because I know the files where I want the swagger-ui tags to be used, I've added a simple filename filter patch to avoid trying to lookup on every single file. That improved the performance to only 2s!

```python
def on_post_page(self, output, page, config, **kwargs):
    """Replace swagger-ui tag with iframe
    Add javascript code to update iframe height
    Create a html with Swagger UI for iframe
    """
    if page.file.name not in ("rest_api", "rest-api"):
        return output
    ...
```

## Proposal

My proposal is:
- Add an option (e.g, `filter_filenames`), which provides an optional list of filenames to match before proceding the processing.
- For backward-compat, if this option is not provided the plugin continue with its current behavior.

What do you think? I can open a PR next week

**Comment by pedro-psb** [comment]
Another similar approach is to mark specific markdown pages using the yaml frontmatter and add a global option to not process a page unless its marked.

```yaml
# some markdown page frontmatter
---
swagger-ui:
  process-page: true
---

# mkdocs.yaml
plugins:
  mkdocs-swagger-ui:
    process_all: false  # default true for compatibility
```
