### ISSUE TITLE
Is it possible to configure Swagger OAuth 2.0 authorization?

### ISSUE THREAD

**Issue by robvanderleek** [blueswen/mkdocs-swagger-ui-tag#4]
Hi there 👋 

In FastAPI there's the option `swagger_ui_init_oauth` to configure [OAuth 2.0 authorization](https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/) for Swagger. For example:

```python
app = FastAPI(
    title='My API',
    description="My description",
    version="0.1.0",
    swagger_ui_init_oauth={
        "usePkceWithAuthorizationCodeGrant": True,
        "clientId": '****',
        "scopes": ['openid', 'email', 'groups'], },
)
```

Is it possible to set the parameters (or the complete dict) from `swagger_ui_init_oauth` using this plugin?
I could not find it in the documentation but maybe I overlooked.

**Comment by blueswen** [comment]
Hi @robvanderleek 

We don't have the feature to set the oauth parameters right now. But I can and the ```ui.initOAuth``` function and arguments into script with a simple approach. Do you think setting these parameters over html tag attribute like below is enough or need to add a dict to plugin options as global default?

```html
<swagger-ui src="./demo/openapi-spec/sample.yaml" 
            usePkceWithAuthorizationCodeGrant="true"
            clientId="****"
            scopes="['openid', 'email', 'groups']" />
```

**Comment by robvanderleek** [comment]
If I check our Swagger page generated by FastAPI (where the OAuth authentication works) it contains this JS snippet in the HTML:
![image](https://user-images.githubusercontent.com/5324924/181365501-f3ceca06-1f52-434b-be16-70c2c39f5ed0.png)

So I guess it should indeed be enough to add the parameters in the HTML tag.
Let me know if something is unclear or you want me to test a branch.

**Comment by blueswen** [comment]
We are supporting setting Swagger UI ```initOauth``` method in ner version v0.4.0. You can check https://blueswen.github.io/mkdocs-swagger-ui-tag/demo/oauth2/ to see how to setting.

If there is something you think could be better please let me know. Thanks for the idea !

**Comment by robvanderleek** [comment]
Thanks for the quick implementation @blueswen !

I'm still struggling a bit with the configuration as somehow the redirect URI has `oauth2-redirect.html` appended while it should just return to the originating mkdocs location (`site/api` in my case).

Do you perhaps know what I'm missing here?

**Comment by blueswen** [comment]
Could you provide the plugin options in ```mkdocs.yml``` and the full swagger-ui tag in your markdown file? I am not very familiar with oauth2, maybe I mess something up.

**Comment by robvanderleek** [comment]
I'm also not an expert 😉 

This is the tag I'm using in the Markdown:
```
<swagger-ui src="/openapi.json" clientId="****" usePkceWithAuthorizationCodeGrant="true" scopes="openid email groups"/>
```

And `mkdocs.yml` is pretty basic:

```
site_name: Self-Service API
site_dir: app/site
theme:
  name: material
  palette:
  - scheme: slate
    primary: light blue
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - scheme: default
    primary: light blue
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: assets/logo.png 
  favicon: assets/logo.png
  features:
    - toc.integrate 

plugins:
  - swagger-ui-tag
  - search

nav:
    - 'index.md'
    - 'auth.md'
    - 'api.md'
    - 'API Endpoints': '/docs/'
```

The last navigation entry is just the Swagger docs (I want to replace that one), the one before that points to the Markdown with the Swagger UI tag.
